### ISSUE TITLE
Lost ability to easily test void based requests

### ISSUE THREAD

**Issue by Stephen-Ross** [jbogard/MediatR#298] opened 2018-07-26 08:12 UTC
I've just updated from 4.0.1 to 5.0.1 and although I was able to smoothly update my code base my testing code hasn't gone as well.

Previously using the `RequestHandler<T>` abstract class to quickly satisfy void based handlers without having to implement the running task myself could be easily tested by simply calling the `IRequestHandler<T>.Handle` method.
Now since the `RequestHandler<T>` class has modified so that the abstract method `HandleCore` has changed to `Handle` and the interface method is implemented as the explicit implementation external code is unable to directly access the `Handle` method.

To test this I am now forced to either cast my class to `IRequestHandler<T, Unit>` or re-implement the handle method so that I do not inherit from `RequestHandler<T>` which renders the use of the provided abstract class of no use.

I'd appreciate any suggestions that you have as I'd still like to use the abstract `RequestHandler<T>` for void based handlers (it was handy to not have to do anything to handle this differently) but I'd also like to be able to test the code without resulting to handling this case any differently.

**Comment by khellang** [comment] 2018-07-26 08:23
I guess this is a dupe of https://github.com/jbogard/MediatR/issues/279? Essentially, you want to be able to call the abstract method directly? The only problem is that it's a source breaking change.

**Comment by Stephen-Ross** [comment] 2018-07-26 08:47
Applogies never noticed that #279 was the same issue.
But I wouldn't advocate a change of the accessibility level of the abstract `Handle` method as was suggested(?) within that issue. I'm worried that the loss of functionality in this regard makes testing these classes not impossible but not nice.
Essentially I would strive to not cast at all within my working code and I'd like to carry this over to my test code as well.

**Comment by jbogard** [comment] 2018-07-26 12:35
You don't need to cast, you can just declare your variable as an interface:

```c#
IRequestHandler<Foo, Bar> handler = new FooBarHandler();
```

You're just losing the `var`-ability

There wasn't a great option here, and it's one of the reasons our teams have just stopped using the "helper" classes - they weren't really helping that much.

**Comment by Stephen-Ross** [comment] 2018-07-26 12:58
Since I construct my classes with `AutoFixture` it led me down the path of having the cast without any other means to achieving the same behaviour since the handler is essentially passed into the test case as an argument.

If the consensus is that this was the best option of a bad bunch I'll likely refactor to simply inherit from `IRequestHandler<T>` in this case. It's not going to stop the use of MediatR for me, but I wanted to make sure that this loss of functionality was documented.

**Closed** 2018-09-15 04:45 UTC
