### ISSUE TITLE
Add support for IAsyncEnumerable<TResponse>

### ISSUE THREAD

**Issue by shekar-balgobin** [jbogard/MediatR#494] opened 2020-02-11 10:32 UTC
Add support for IAsyncEnumerable<TResponse> to request handling. IRequestHandler currently only supports Task<TResponse>. This would be a great feature given the move to .NET Core 3 and C#8.

**Comment by jbogard** [comment] 2020-02-13 13:44
Duplicate of #458

**Closed by jbogard** 2020-02-13 13:44 UTC
