### ISSUE TITLE
Handler not found

### ISSUE THREAD

**Issue by darthg8r** [jbogard/MediatR#547] opened 2020-08-19 15:24 UTC
I'm trying to register a generic request handler for a generic request, but I'm getting the error below when calling 

```
await _mediator.Send(new ExchangeOrderRequest<ExchangeOrderResponseSuccessEvent>());
```

System.InvalidOperationException: Handler was not found for request of type MediatR.IRequestHandler`2[MyNamespace.ExchangeOrderRequest`1[MyNamespace.ExchangeOrderResponseSuccessEvent],MediatR.Unit]. Register your handlers with the container. See the samples in GitHub for examples.

As side note, for giggles, I was able to inject an instance of IRequestHandler<ExchangeOrderRequest< ExchangeOrderResponseSuccessEvent>> into a controller just fine.

```
// Some assembly scanning, doesn't find my handler
services.AddMediatR(typeof(Startup), typeof(ExchangeOrderRequest), typeof(IDocumentMessage), typeof(OrderExecution.Handler));

// Try to manually add the handler.  Still doesn't find it
services.AddTransient<IRequestHandler<ExchangeOrderRequest<ExchangeOrderResponseSuccessEvent>>, ExchargeOrderRequestHandler<ExchangeOrderResponseSuccessEvent, ExchangeOrderRequest<ExchangeOrderResponseSuccessEvent>>>();




public class ExchargeOrderRequestHandler<TEvent, TRequest> : IRequestHandler<TRequest> 
	where TRequest : ExchangeOrderRequest<TEvent> 
	where TEvent : ExchangeOrderEvent
{
     // Stuff
}`

public class ExchangeOrderRequest<T>: DocumentMessage, IRequest where T: ExchangeOrderEvent
{
     // Stuff
}

public class ExchangeOrderEvent : IEvent
{
      // Stuff
 
		
}
```

What am I missing here?

**Comment by lilasquared** [comment] 2020-08-19 18:26
can you post a small repo that reproduces this?  I know that constrained generics are not supported by the dotnet core DI but if you're registering them manually i'm not sure why it wouldn't work.  It could be that you have to create a non-generic class and register that.  Like:

```csharp
public class ExchangeOrderSuccessHandler : IRequestHandler<ExchangeOrderRequest<ExchangeOrderSuccessEvent>> { ... }
```

**Comment by darthg8r** [comment] 2020-08-19 20:43
@lilasquared Done:  https://github.com/darthg8r/GenericMediatorHandler

**Comment by darthg8r** [comment] 2020-08-19 21:40
It looks like there's something off in the handler resolution.  Explicitly adding Unit as a generic argument to the request handler seems to have fixed it..

```
services.AddTransient<IRequestHandler<ExchangeOrderRequest<ExchangeOrderResponseSuccessEvent>, Unit>, ExchargeOrderRequestHandler<ExchangeOrderResponseSuccessEvent, ExchangeOrderRequest<ExchangeOrderResponseSuccessEvent>>>();




public class ExchargeOrderRequestHandler<TEvent, TRequest> : IRequestHandler<TRequest, Unit> 
	where TRequest : ExchangeOrderRequest<TEvent> 
	where TEvent : ExchangeOrderEvent
{
     // Stuff
}
```

If I have some time, I'll see if I can find the actual bug in the library.

**Comment by lilasquared** [comment] 2020-08-19 22:07
Looks like you don't even need `Unit` in the class definition, just in the registration.  I think this is the same issue I mentioned above where dotnet core DI doesn't support generic registrations.  When you use the `IRequestHandler<T>` interface I don't think the DI can properly map it to `IRequestHandler<T, Unit>`.  I don't know for sure but thats my guess.  If you use Lamar or another more mature DI you most likely won't have this problem.

**Comment by HunteRoi** [comment] 2021-01-14 13:12
Hey there, we are having the same problem due to the DI container of .NET. Is there any chance that this problem would be addressed somewhere?

**Comment by zachpainter77** [comment] 2021-05-10 23:24
https://github.com/jbogard/MediatR/issues/635

I have a similar issue... I was able to solve it by using the AutoFac container but couldn't get it to work using the default container.

**Comment by lesnerd** [comment] 2021-07-13 11:17
I have the same issue. Will it be solved?

**Comment by jbogard** [comment] 2021-07-13 13:10
Use a different container, the Microsoft DI container often can't handle these edge cases, and this is one of them. It can't handle partially closed generic types.

Otherwise, it might be fixed in the registration side of things, we might be able to forward registrations perhaps?

**Closed** 2022-09-30 09:08 UTC
